# Generated by Django 5.2.7 on 2025-10-19 18:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('type', models.CharField(choices=[('CHECKING', 'Conta Corrente'), ('SAVINGS', 'Poupança'), ('CREDIT_CARD', 'Cartão de Crédito'), ('CASH', 'Dinheiro'), ('INVESTMENT', 'Investimentos')], max_length=20, verbose_name='Tipo')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Inicial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['-created_at'],
            },
        ),
    ]
